### ISSUE TITLE
Transaction appearing twice on the confirmation page

### ISSUE THREAD

**Issue by ankitnagarsheth** [TechnicalWebAnalytics/dataLayer-shopify#46]
Transaction event is appearing two times on the confirmation page. How can I rectify that? Appreciate your help on this.

![32612280-096d90aef59ed42445d00047e5ab059e](https://user-images.githubusercontent.com/16673852/191368290-e0aae52e-60ce-41c1-b851-ba9d20a58e96.png)

**Comment by adventuretocode** [comment]
@ankitnagarsheth   that event trigger twice from GTM side.  this was not issue with dataLayers.

**Comment by ankitnagarsheth** [comment]
Looks good. Some setup mistake on my end.

**Comment by ankitnagarsheth** [comment]
resolved

**Comment by adventuretocode** [comment]
@ankitnagarsheth   i used same data layer but Transaction  event not happen.

are you rendering main delayer file into the theme layout file ? or somethings else ?

**Comment by adventuretocode** [comment]
@ankitnagarsheth   Remove cart work for you ?
